account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/<int:user_id>/', views.user_dashboard, name='dashboard'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('phone-login/', views.phone_login, name='phone_login'),
    path('verify/', views.verify, name='verify'),
    path('follow/', views.follow, name='follow'),
    path('unfollow/', views.unfollow, name='unfollow'),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('add-post/<int:user_id>/', views.add_post, name='add_post'),
    path('post-delete/<int:user_id>/<int:post_id>/', views.post_delete, name ='post_delete'),
    path('post-edit/<int:user_id>/<int:post_id>/', views.post_edit, name='post_edit'),
    path('add-reply/<int:post_id>/<int:comment_id>', views.add_reply, name='add_reply'),
    path('like/<int:post_id>/', views.post_like, name = 'post_like'),

]

social_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('account/', include('account.urls', namespace='account')),
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'posts:all_posts' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'account:logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'account:login' %}">Login</a>
        <a class="nav-item nav-link active" href="{% url 'account:phone_login' %}">Phone Login</a>
        <a class="nav-item nav-link active" href="{% url 'account:register' %}">Register</a>
        {% endif %}
    </div>
</nav>